In [5]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==4)
y=np.where(arr==6)
print(y)
print(x)


(array([1, 4]),)
(array([5]),)


In [3]:
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [11]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,3,side='left')
print(x)



4


In [13]:
arr=np.array([0,1,5,3,6,7,2])
x1=np.searchsorted(arr,3,side='left')
print(x1)

2


In [15]:
arr=np.array([0,1,2,2,7,8,9])
x3=np.searchsorted(arr,8,side='right')
print(x3)

6


In [17]:
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [19]:
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [30]:
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
narr=arr>42
newarr=arr[narr]
print(arr)
print(x)
print(narr)
print(newarr)

[41 42 43 44]
[True, False, True, False]
[False False  True  True]
[43 44]


In [32]:
arr=np.array([31,78,69,88])
x=[False,True,True,False]
newarr=arr[x]
print(x)
print(newarr)


[False, True, True, False]
[78 69]
